steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['get', '-u', 
  'cloud.google.com/go/pubsub',
  'google.golang.org/api/option',
  'google.golang.org/grpc',
  'google.golang.org/grpc/codes',
  ]
  env: ['PROJECT_ROOT=app']
- name: 'gcr.io/cloud-builders/go'
  args: ['build', 'app']
  env: ['PROJECT_ROOT=app']
- name: 'ubuntu'
  args: ['chmod', '+x', 'app']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', 
  '-t', 'gcr.io/${PROJECT_ID}/${_REPO_PREFIX}/${REPO_NAME}:$BRANCH_NAME$TAG_NAME', 
  '-t', 'gcr.io/${PROJECT_ID}/${_REPO_PREFIX}/${REPO_NAME}:$SHORT_SHA', 
  '-t', 'gcr.io/${PROJECT_ID}/${_REPO_PREFIX}/${REPO_NAME}', 
  '.' ]
images:
- 'gcr.io/${PROJECT_ID}/${_REPO_PREFIX}/${REPO_NAME}'
tags: [$BRANCH_NAME$TAG_NAME, $REVISION_ID, '$REPO_NAME']
substitutions:
  _REPO_PREFIX: makz-labs