apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: ${APPLICATION}
  name: ${APPLICATION}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ${APPLICATION}
  template:
    metadata:
      labels:
        run: ${APPLICATION}
    spec:
      containers:
      - image: ${CONTAINER_IMAGE}
        name: ${APPLICATION}
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        env:
        - name: PUBLISH
          value: "true"
        - name: SUBSCRIBE
          value: "true"
        - name: "SUB_SUFFIX"
          value: 4
        - name: "GOOGLE_APPLICATION_CREDENTIALS"
          value: "/var/run/secret/cloud.google.com/$APPLICATION-sa-key.json"
        - name: "PROJECT_ID"
          valueFrom:
            configMapKeyRef:
              name: project-id
              key: project-id
        - name: "APP_SA_EMAIL"
          valueFrom:
            configMapKeyRef:
              name: ${APPLICATION}-sa
              key: sa-email
        volumeMounts:
            - name: "service-account"
              mountPath: "/var/run/secret/cloud.google.com"
      volumes:
        - name: "service-account"
          secret:
            secretName: "${APPLICATION}"